# Generated by Django 2.2.6 on 2019-11-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
