# Generated by Django 2.2.6 on 2019-11-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
