# Generated by Django 2.2.6 on 2019-12-04 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_imagenperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenperfil',
            name='author',
        ),
        migrations.AddField(
            model_name='imagenperfil',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
