# Generated by Django 2.2.6 on 2019-12-05 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191204_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenPerfil',
        ),
    ]
