# Generated by Django 2.2.6 on 2019-11-04 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserName', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=15)),
                ('Nombre', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
    ]
