# Generated by Django 2.2.6 on 2019-11-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191104_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='imagenPortada',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
