# Generated by Django 2.2.6 on 2019-11-06 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191105_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen1',
            field=models.ImageField(blank=True, upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ),
    ]
