# Generated by Django 2.2.6 on 2019-11-06 03:27

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191105_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen1',
            field=models.ImageField(blank=True, upload_to=django.db.models.fields.Field.value_to_string),
        ),
    ]
