# Generated by Django 2.2.6 on 2019-11-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_gameforwindows'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shortext',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
