# Generated by Django 2.2.6 on 2019-11-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_shortext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shortext',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
