# Generated by Django 2.2.6 on 2019-11-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191118_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gameForWindows',
            field=models.FileField(blank=True, null=True, upload_to='games/'),
        ),
    ]
